### ISSUE TITLE
 Exception: Faraday::ConnectionFailed

### ISSUE THREAD

**Issue by laurentiubanica** [janmg/logstash-input-azure_blob_storage#17]
Plugin: <LogStash::Inputs::AzureBlobStorage container=>"insights-logs-networksecuritygroupflowevent", logtype=>"nsgflowlog", interval=>60, id=>"887c74298e1b2c107836e7dc02c22a18c516c2171c18d14b7e0b4b34158ca261", connection_string=><password>, prefix=>"resourceId=/", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_e8fc0f24-18ab-4047-8a59-75c0f06e9629", enable_metric=>true, charset=>"UTF-8">, dns_suffix=>"core.windows.net", registry_path=>"data/registry.dat", registry_create_policy=>"resume", file_head=>"{\"records\":[", file_tail=>"]}">
  Error: Connection reset by peer
  Exception: Faraday::ConnectionFailed
  Stack: org/jruby/ext/openssl/SSLSocket.java:893:in `sysread_nonblock'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/buffering.rb:182:in `read_nonblock'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:175:in `rbuf_fill'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:157:in `readuntil'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/protocol.rb:167:in `readline'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:40:in `read_status_line'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http/response.rb:29:in `read_new'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1504:in `block in transport_request'
org/jruby/RubyKernel.java:1193:in `catch'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1501:in `transport_request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1474:in `request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1467:in `block in request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:914:in `start'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1465:in `request'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1223:in `get'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:85:in `perform_request'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:43:in `block in call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.17.0/lib/faraday/adapter/net_http.rb:38:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/http_response_helper.rb:27:in `set_up_response'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/http/http_request.rb:149:in `call'
org/jruby/RubyMethod.java:116:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/http/signer_filter.rb:28:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/service.rb:36:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/filtered_service.rb:34:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/signed_service.rb:41:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-common-1.1.0/lib/azure/storage/common/service/storage_service.rb:60:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-blob-1.1.0/lib/azure/storage/blob/blob_service.rb:179:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-storage-blob-1.1.0/lib/azure/storage/blob/blob.rb:106:in `get_blob'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.11.1/lib/logstash/inputs/azure_blob_storage.rb:260:in `partial_read_json'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.11.1/lib/logstash/inputs/azure_blob_storage.rb:199:in `block in run'
org/jruby/RubyHash.java:1417:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_blob_storage-0.11.1/lib/logstash/inputs/azure_blob_storage.rb:191:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:321:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:313:in `block in start_input'

**Comment by janmg** [comment]
Faraday is the HTTP client that connects to the blobstore to fetch the blocks. It works most of the time, but sometimes the blobs don't return. I would like to update the Gemspec to update the Faraday version, but logstash is also using Faraday and there is a version conflict that I can't solve.

To overcome this, there is a a 1..3 loop to retry in case Faraday fails. There is a bug that got fixed in version 0.11.4 where the loop would be executed always instead of just when it fails. This creates extra load/traffic and doesn't catch the Faraday connection issue. Updating to the latest version may help a bit, but the real issue is between Faraday and the BlobStorage.

**Comment by laurentiubanica** [comment]
I have upgraded the plugin to the latest version. So, the problem remains (the log I provided is generated after update).
I noticed that, in the end, the connection is reestablished and we get events. 
This error is intermittent. We get it from time to time.

**Comment by janmg** [comment]
I pushed 0.11.7, I tested it with my own blob set to archive and when the file is tried to be read, the exception will trigger and I set the read size immediately to the file size, so it won't be retried. For now that's going to be the default unless somebody needs different behaviour, then I will invent a new parameter show_must_go_on => false

I also pushed some code that I didn't publish in February. It introduces the skip_learning so that you can choose to not read a random blob to learn the json format. For NSG these will be default anyway.

**Comment by laurentiubanica** [comment]
Ok. Thank you very much. I'll update to the new version.

**Comment by janmg** [comment]
Guess it's fixed
